# Generated by Django 5.2 on 2025-12-30 18:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount threshold', max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount threshold', max_digits=12, null=True)),
                ('required_roles', models.JSONField(default=list, help_text='Roles that can approve (empty = any admin)')),
                ('required_departments', models.JSONField(default=list, help_text='Departments this rule applies to (empty = all)')),
                ('working_hours_only', models.BooleanField(default=False, help_text='Require approval only during working hours')),
                ('working_hours_start', models.TimeField(blank=True, default='09:00', null=True)),
                ('working_hours_end', models.TimeField(blank=True, default='17:00', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='inventory_a_is_acti_f2363e_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(help_text='Resource owner who controls access', on_delete=django.db.models.deletion.CASCADE, related_name='owned_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('access', 'Resource Access'), ('grant', 'Permission Granted'), ('revoke', 'Permission Revoked'), ('modify', 'Permission Modified'), ('create', 'Resource Created'), ('update', 'Resource Updated'), ('delete', 'Resource Deleted')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_logs', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('required_approval_date', models.DateTimeField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approval_rule_applied', models.CharField(blank=True, help_text='Which rule triggered approval requirement', max_length=200)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('share', 'Share')], help_text='Type of permission granted', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(help_text='Resource owner who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(help_text='The inventory item/resource', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(help_text='User granted permission', on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('failed_login', 'Failed Login Attempts'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('suspicious_activity', 'Suspicious Activity'), ('policy_violation', 'Policy Violation'), ('data_breach', 'Data Breach'), ('system_compromise', 'System Compromise')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Additional alert details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('startup', 'System Startup'), ('shutdown', 'System Shutdown'), ('config_change', 'Configuration Change'), ('security_event', 'Security Event'), ('backup', 'Backup'), ('restore', 'Restore'), ('maintenance', 'Maintenance'), ('error', 'Error'), ('warning', 'Warning')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Additional event details')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Store username in case user is deleted', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('share', 'Share'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('import', 'Import')], max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource accessed', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of resource accessed', max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='inventory_b_status_951b9f_idx'), models.Index(fields=['triggered_by', 'started_at'], name='inventory_b_trigger_10b272_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'is_active'], name='inventory_i_owner_i_f1b84a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['department', 'category'], name='inventory_i_departm_8c851b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['created_at'], name='inventory_i_created_c50f70_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['resource', 'timestamp'], name='inventory_p_resourc_d601a1_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['user', 'timestamp'], name='inventory_p_user_id_f6c84e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['action', 'timestamp'], name='inventory_p_action_b73cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'requested_at'], name='inventory_p_status_3f6a33_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['requested_by', 'status'], name='inventory_p_request_0bb478_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['total_amount'], name='inventory_p_total_a_06cccb_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['resource', 'user', 'is_active'], name='inventory_r_resourc_e59ece_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['user', 'is_active'], name='inventory_r_user_id_c41e94_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['expires_at'], name='inventory_r_expires_b2d3b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepermission',
            unique_together={('resource', 'user', 'permission_type')},
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['alert_type', 'severity', 'is_resolved'], name='inventory_s_alert_t_5ad5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['is_resolved', 'created_at'], name='inventory_s_is_reso_226f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['user', 'created_at'], name='inventory_s_user_id_28927a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='inventory_s_event_t_c761f6_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['severity', 'timestamp'], name='inventory_s_severit_105b60_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['timestamp'], name='inventory_s_timesta_367bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='inventory_u_user_id_d0de62_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['username', 'timestamp'], name='inventory_u_usernam_8499e9_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', 'timestamp'], name='inventory_u_action_cbb8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='inventory_u_resourc_620378_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='inventory_u_ip_addr_022481_idx'),
        ),
    ]
