# Generated by Django 5.2 on 2025-12-29 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of permission strings')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_ro_name_183ba5_idx'), models.Index(fields=['is_active'], name='accounts_ro_is_acti_8f899c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/identifier for the data resource', max_length=200, unique=True)),
                ('classification', models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top Secret', 'Top Secret')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource (e.g., 'document', 'database', 'api_endpoint')", max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Identifier for the specific resource', max_length=255)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-classified_at'],
                'indexes': [models.Index(fields=['classification'], name='accounts_da_classif_ad68df_idx'), models.Index(fields=['resource_type', 'resource_id'], name='accounts_da_resourc_18bb7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict, help_text='Policy conditions (role, department, location, time, etc.)')),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_classification', models.CharField(blank=True, choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top Secret', 'Top Secret')], help_text='Minimum classification level required', max_length=20)),
                ('action', models.CharField(help_text="Action allowed (e.g., 'read', 'write', 'delete', 'execute')", max_length=100)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies are evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permission Policies',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='accounts_pe_is_acti_daa0fd_idx'), models.Index(fields=['resource_type', 'resource_classification'], name='accounts_pe_resourc_3a9797_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_roles', models.JSONField(default=list, help_text='Current roles of the user')),
                ('reason', models.TextField(help_text='Reason for role change request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the temporary role should expire', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='role_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='accounts.role')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_ro_user_id_190032_idx'), models.Index(fields=['status', 'requested_at'], name='accounts_ro_status_d5e464_idx'), models.Index(fields=['expires_at'], name='accounts_ro_expires_1f9677_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_role', models.ForeignKey(help_text='Lower-level role that inherits from parent', on_delete=django.db.models.deletion.CASCADE, related_name='parent_roles', to='accounts.role')),
                ('parent_role', models.ForeignKey(help_text='Higher-level role', on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='accounts.role')),
            ],
            options={
                'verbose_name_plural': 'Role Hierarchies',
                'indexes': [models.Index(fields=['parent_role', 'child_role'], name='accounts_ro_parent__0b66ac_idx')],
                'unique_together': {('parent_role', 'child_role')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for temporary roles', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'role'], name='accounts_us_user_id_5c3bd8_idx'), models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_2517ab_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_e3430f_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
